/**
 * Generate a human-readable term reference for the BatteryPass Consortium SAMM
 * properties our battery ontology aligns to.
 *
 * The SAMM aspect models identify terms by URN (urn:samm:io.BatteryPass.*#prop),
 * which a browser cannot dereference — clicking a SAMM alignment in the
 * ref.openepcis.io browser lands on a blank window. This script mirrors the
 * `samm:preferredName` / `samm:description` text of exactly the SAMM properties
 * referenced as SKOS targets in extensions/eu/battery/json/battery.json into a
 * small Turtle document keyed by the full URN. copy-ontologies.ts converts it to
 * public/ontologies/external/samm-batterypass.jsonld (same pipeline as the bpr
 * vocab), so the browser can render a real term card (label + Consortium
 * definition) for a SAMM URN instead of an empty page.
 *
 * The definitions are the BatteryPass Consortium's (github.com/batterypass,
 * CC-BY-4.0); this is a derived reference copy for browsing/alignment, mirroring
 * how the GEFEG BatteryPass-Ready (bpr) vocab is framed.
 *
 * Output: extensions/eu/battery/vocab/batterypass-samm-terms.ttl
 * Run: pnpm run build:batterypass-samm-terms
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { homedir } from "os";
import { Parser } from "n3";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const BATTERY_JSON = join(ROOT, "extensions/eu/battery/json/battery.json");
const OUT = join(ROOT, "extensions/eu/battery/vocab/batterypass-samm-terms.ttl");
const SAMM_ROOT =
  process.env.BATTERYPASS_ROOT ?? join(homedir(), "Documents/projects/BatteryPassDataModel");

// The SAMM property URNs our alignments actually reference — the only terms a
// user can click through to, so the only ones worth a reference card.
const referenced = [
  ...new Set(
    (readFileSync(BATTERY_JSON, "utf-8").match(/urn:samm:io\.BatteryPass\.[^"\s]+/g) ?? []).filter(
      (u) => u.includes("#"),
    ),
  ),
].sort();

// Humanize a camelCase / PascalCase local name into a fallback label.
function humanize(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/\s+/g, " ")
    .replace(/^./, (c) => c.toUpperCase())
    .trim();
}

const esc = (s: string) =>
  s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t");

function walkTtl(dir: string, out: string[] = []): string[] {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) walkTtl(p, out);
    else if (e.endsWith(".ttl")) out.push(p);
  }
  return out;
}

/** urn -> { label (preferredName), definition (description) }, from the checkout. */
function loadSammText(): Map<string, { label?: string; definition?: string }> {
  const map = new Map<string, { label?: string; definition?: string }>();
  if (!existsSync(SAMM_ROOT)) return map;
  const parser = new Parser();
  for (const f of walkTtl(SAMM_ROOT)) {
    let quads;
    try {
      quads = parser.parse(readFileSync(f, "utf-8"));
    } catch {
      continue;
    }
    for (const q of quads) {
      const pred = q.predicate.value;
      if (!pred.endsWith("#preferredName") && !pred.endsWith("#description")) continue;
      if (q.object.termType !== "Literal") continue;
      const lang = (q.object as unknown as { language?: string }).language ?? "";
      if (lang && lang.toLowerCase() !== "en") continue;
      // Keyed by the exact URN, so Property vs Characteristic (same name, diff
      // case) never collide; the referenced set only ever pulls the real one.
      const urn = q.subject.value;
      const val = q.object.value.trim();
      const entry = map.get(urn) ?? {};
      if (pred.endsWith("#preferredName")) entry.label = val;
      else if (val.length >= 3) entry.definition = val; // skip stub text like "s"
      map.set(urn, entry);
    }
  }
  return map;
}

if (!existsSync(SAMM_ROOT) && existsSync(OUT)) {
  console.log(`  [skip] SAMM checkout not at ${SAMM_ROOT}; keeping existing ${OUT}`);
  process.exit(0);
}

const text = loadSammText();

const lines: string[] = [
  "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
  "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
  "@prefix skos: <http://www.w3.org/2004/02/skos/core#> .",
  "@prefix dcterms: <http://purl.org/dc/terms/> .",
  "",
  "# BatteryPass Consortium SAMM property reference (github.com/batterypass, CC-BY-4.0).",
  "# Derived browsable copy of the preferredName/description of the SAMM properties our",
  "# battery ontology aligns to. Generated by scripts/build-batterypass-samm-terms.ts.",
  "",
];

let withDef = 0;
for (const urn of referenced) {
  const local = urn.slice(urn.lastIndexOf("#") + 1);
  const t = text.get(urn) ?? {};
  const label = t.label && t.label.length ? t.label : humanize(local);
  lines.push(`<${urn}>`);
  lines.push("    a rdf:Property ;");
  lines.push(`    rdfs:label "${esc(label)}"@en ;`);
  if (t.definition) {
    lines.push(`    rdfs:comment "${esc(t.definition)}"@en ;`);
    lines.push(`    skos:definition "${esc(t.definition)}"@en ;`);
    withDef++;
  }
  lines.push(
    `    dcterms:source <https://github.com/batterypass/BatteryPassDataModel> .`,
  );
  lines.push("");
}

writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`Wrote ${OUT}`);
console.log(`  ${referenced.length} referenced SAMM terms; ${withDef} with a Consortium definition`);
if (!text.size) {
  console.log(`  [warn] SAMM checkout not found at ${SAMM_ROOT} — labels humanized, no definitions.`);
}
