#!/usr/bin/env tsx
/**
 * Convert any JSON-LD document to Turtle.
 *
 * Works on plain JSON-LD vocabularies (e.g. gs1RailVoc.jsonld), JSON-LD
 * SHACL shape graphs (e.g. Rail-SHACL.json), or any other JSON-LD doc that
 * the upstream `jsonld` library can flatten to N-Quads. Output uses the
 * standard prefix declarations that show up most often in vocabulary and
 * SHACL files, so the produced .ttl is human-readable rather than raw IRIs.
 *
 * Usage:
 *
 *   tsx jsonld-to-ttl.ts <input> [output]
 *
 *     input   = URL  (https://… returning application/ld+json)
 *             | file path (.jsonld)
 *             | "-"  (read stdin)
 *
 *     output  = file path
 *             | omitted → stdout
 *
 * Examples:
 *
 *   tsx jsonld-to-ttl.ts \
 *       https://gs1-epcis-reg.org/rail/voc/data/Rail-SHACL.json \
 *       Rail-SHACL.ttl
 *
 *   tsx jsonld-to-ttl.ts ./Rail-EPCIS-SHACL-Generic.json > Rail-EPCIS-SHACL-Generic.ttl
 *
 *   curl -s https://example.com/foo.jsonld | tsx jsonld-to-ttl.ts -
 *
 * Requires (as a one-time setup):
 *
 *   pnpm add -D tsx jsonld n3
 *   # or:  npm i -D tsx jsonld n3
 */

import { promises as fs } from "node:fs";
import { Parser as N3Parser, Store, Writer as N3Writer } from "n3";
import jsonld from "jsonld";

// Default prefix table. Add or override via `EXTRA_PREFIXES` below if your
// document uses other namespaces — N3 will inline-IRI anything it doesn't
// have a prefix for, so missing entries don't break output, only readability.
const PREFIXES: Record<string, string> = {
  // SHACL
  sh: "http://www.w3.org/ns/shacl#",
  // RDF / OWL / XSD
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
  rdfs: "http://www.w3.org/2000/01/rdf-schema#",
  owl: "http://www.w3.org/2002/07/owl#",
  xsd: "http://www.w3.org/2001/XMLSchema#",
  skos: "http://www.w3.org/2004/02/skos/core#",
  // Dublin Core
  dc: "http://purl.org/dc/terms/",
  dcterms: "http://purl.org/dc/terms/",
  dc11: "http://purl.org/dc/elements/1.1/",
  // VANN / VOAF (vocabulary metadata)
  vann: "http://purl.org/vocab/vann/",
  voaf: "http://www.w3.org/ns/voaf#",
  sw: "http://www.w3.org/2003/06/sw-vocab-status/ns#",
  // Common upstream vocabularies
  schema: "https://schema.org/",
  gs1: "https://ref.gs1.org/voc/",
  epcis: "https://ref.gs1.org/epcis/",
  cbv: "https://ref.gs1.org/cbv/",
  // SEMICeu Core Vocabularies
  cv: "http://data.europa.eu/m8g/",
  cccev: "http://data.europa.eu/m8g/",
  locn: "http://www.w3.org/ns/locn#",
  adms: "http://www.w3.org/ns/adms#",
  cpsv: "http://purl.org/vocab/cpsv#",
  // GS1 Rail (sectoral upstream)
  rail: "https://gs1-epcis-reg.org/rail/voc/data#",
};

const EXTRA_PREFIXES: Record<string, string> = {
  // Add your project-specific prefixes here, e.g.:
  // dpp:  "https://ref.openepcis.io/extensions/common/core/",
};

async function readInput(arg: string): Promise<string> {
  if (arg === "-") {
    const chunks: Buffer[] = [];
    for await (const chunk of process.stdin) chunks.push(chunk as Buffer);
    return Buffer.concat(chunks).toString("utf8");
  }
  if (/^https?:\/\//i.test(arg)) {
    const res = await fetch(arg, { headers: { Accept: "application/ld+json, application/json" } });
    if (!res.ok) throw new Error(`fetch ${arg}: HTTP ${res.status}`);
    return await res.text();
  }
  return await fs.readFile(arg, "utf8");
}

async function jsonldToTurtle(jsonldText: string, sourceLabel: string): Promise<string> {
  const doc = JSON.parse(jsonldText);

  // Step 1: JSON-LD → N-Quads (the lowest-common-denominator RDF serialisation).
  const nquads = (await jsonld.toRDF(doc, { format: "application/n-quads" })) as unknown as string;

  // Step 2: parse N-Quads with N3 so we have an in-memory store.
  const store = new Store();
  await new Promise<void>((resolve, reject) => {
    const parser = new N3Parser({ format: "application/n-quads" });
    parser.parse(nquads, (err, quad) => {
      if (err) return reject(err);
      if (quad) store.addQuad(quad);
      else resolve();
    });
  });

  // Step 3: write Turtle with prefix declarations so the output is readable.
  const writer = new N3Writer({ prefixes: { ...PREFIXES, ...EXTRA_PREFIXES } });
  return await new Promise<string>((resolve, reject) => {
    writer.addQuads(store.getQuads(null, null, null, null));
    writer.end((err, result) => {
      if (err) return reject(err);
      resolve(
        [
          `# Turtle serialisation of ${sourceLabel}`,
          `# Generated by jsonld-to-ttl.ts at ${new Date().toISOString()}.`,
          "",
          result,
        ].join("\n"),
      );
    });
  });
}

async function main(): Promise<void> {
  const [, , input, output] = process.argv;
  if (!input) {
    process.stderr.write(
      "Usage: tsx jsonld-to-ttl.ts <input> [output]\n" +
        "  <input>  URL, file path, or '-' to read stdin\n" +
        "  [output] file path; omit for stdout\n",
    );
    process.exit(2);
  }

  const text = await readInput(input);
  const ttl = await jsonldToTurtle(text, input);

  if (output && output !== "-") {
    await fs.writeFile(output, ttl, "utf8");
    process.stderr.write(`Wrote ${output} (${ttl.length} bytes)\n`);
  } else {
    process.stdout.write(ttl);
  }
}

main().catch((err) => {
  process.stderr.write(`error: ${err.message}\n`);
  process.exit(1);
});
