#!/usr/bin/env bash
# Seed the 7 manufacturer Organization records to the configured DLR.
#
# Reads every *.jsonld in extensions/common/core/examples/organizations/
# (generated by scripts/generate-org-seeds.py) and POSTs each to
# `${DL_URL}/organizations`. 409 conflicts are treated as SKIP so the
# script is safely re-runnable.
#
# Env:
#   BRUNO_PW            — admin password in the openepcis realm
#   BRUNO_CLIENT_SECRET — secret for backend-service in the openepcis realm

set -euo pipefail

DL_URL="${DL_URL:-https://id.dev.epcis.cloud}"
AUTH_URL="${AUTH_URL:-https://auth.dev.epcis.cloud}"
REALM="${REALM:-openepcis}"
CLIENT_ID="${CLIENT_ID:-backend-service}"
USERNAME="${USERNAME:-admin}"

red()    { printf "\033[31m%s\033[0m\n" "$*"; }
green()  { printf "\033[32m%s\033[0m\n" "$*"; }
yellow() { printf "\033[33m%s\033[0m\n" "$*"; }

if [[ -z "${BRUNO_PW:-}" || -z "${BRUNO_CLIENT_SECRET:-}" ]]; then
  red "Set BRUNO_PW and BRUNO_CLIENT_SECRET." >&2
  exit 1
fi

TOKEN=$(curl -sk -X POST "$AUTH_URL/realms/$REALM/protocol/openid-connect/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  --data-urlencode "grant_type=password" \
  --data-urlencode "client_id=$CLIENT_ID" \
  --data-urlencode "client_secret=$BRUNO_CLIENT_SECRET" \
  --data-urlencode "username=$USERNAME" \
  --data-urlencode "password=$BRUNO_PW" \
  --data-urlencode "scope=openid roles profile" \
  | jq -r '.access_token // empty')
[[ -z "$TOKEN" ]] && { red "Token fetch failed." >&2; exit 1; }

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ORG_DIR="$REPO_ROOT/extensions/common/core/examples/organizations"

for src in "$ORG_DIR"/*.jsonld; do
  slug=$(basename "$src" .jsonld)
  gln=$(jq -r '.globalLocationNumber' "$src")
  code=$(curl -sk -X POST "$DL_URL/organizations" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -H "isAnonymousAccessAllowed: true" \
    --data-binary @"$src" \
    -w "%{http_code}" -o /tmp/r.json)
  case "$code" in
    20[0-2]) green "$slug ($gln)  POST → $code" ;;
    409)     yellow "$slug ($gln)  POST → 409 (already present)" ;;
    *)       red "$slug ($gln)  POST → $code"; head -c 300 /tmp/r.json; echo ;;
  esac
done
