/**
 * Sync the CIRPASS-2 EUDPP Core Ontology mirror (extensions/upstream/cirpass2-eudpp).
 *
 * Fetches the published module exports of the EUDPP Core Ontology
 * (https://w3id.org/eudpp#) from the Semantic Treehouse hub via the W3ID
 * redirects and merges them verbatim — upstream IRIs preserved, nothing
 * rebranded — into ontology/eudpp.ttl, the single source file the build
 * pipeline parses into json/eudpp.json (same pattern as the GS1 Rail mirror,
 * which merges upstream JSON-LD into gs1RailVoc.ttl).
 *
 * This mirror exists so ref.openepcis.org can index and render the EUDPP terms
 * as a first-class Layer-2 upstream vocabulary. Our own ontology still
 * references eudpp terms by IRI only — no owl:imports, no class adoption
 * (see extensions/common/interop/docs/CIRPASS2_ALIGNMENT.md).
 *
 * Upstream license: Apache License 2.0 (CC BY 4.0 fallback when treated as a
 * document), (c) CIRPASS-2 project / TalTech. The mirror keeps that license.
 *
 * NETWORK: hits dpp.vocabulary-hub.eu. Run deliberately (like sync:vocab and
 * sync:rail), not as part of build.
 *
 * Output: extensions/upstream/cirpass2-eudpp/ontology/eudpp.ttl
 * Run: pnpm run sync:eudpp
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { Parser, Writer, Store, type Quad } from "n3";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const OUT = join(ROOT, "extensions/upstream/cirpass2-eudpp/ontology/eudpp.ttl");

const W3ID_BASE = "https://w3id.org/eudpp";
// CORE plus its owl:imports closure. LCA is published alongside but not (yet)
// listed in CORE's imports (v2.0.5) — the alignment doc counts it as a content
// module and our oec: EPD/LCA pointers target it, so it is fetched explicitly.
const MODULES = ["", "ACTOR", "CON", "EVENT", "IDENT", "MAT", "P_DPP", "SOC", "COMP", "LCA"] as const;

const RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
const RDFS = "http://www.w3.org/2000/01/rdf-schema#";
const OWL = "http://www.w3.org/2002/07/owl#";
const DCT = "http://purl.org/dc/terms/";

async function fetchModule(suffix: string): Promise<string> {
  const url = suffix ? `${W3ID_BASE}/${suffix}` : W3ID_BASE;
  const res = await fetch(url, { headers: { Accept: "text/turtle" }, redirect: "follow" });
  if (!res.ok) throw new Error(`${url} -> HTTP ${res.status}`);
  return res.text();
}

const store = new Store();
const moduleLog: string[] = [];
let coreVersion = "";
let coreIssued = "";

for (let i = 0; i < MODULES.length; i++) {
  const suffix = MODULES[i];
  const ttl = await fetchModule(suffix);
  // Per-module blank-node prefix so anonymous OWL constructs (restrictions,
  // unions) from different exports can never collide in the merged store.
  const quads: Quad[] = new Parser({ blankNodePrefix: `_:m${i}_` }).parse(ttl);

  const ontologyIri = quads.find(
    (q) => q.predicate.value === `${RDF}type` && q.object.value === `${OWL}Ontology`,
  )?.subject.value;
  const val = (s: string | undefined, p: string) =>
    s ? quads.find((q) => q.subject.value === s && q.predicate.value === p)?.object.value : undefined;
  const label = val(ontologyIri, `${RDFS}label`) ?? val(ontologyIri, `${DCT}title`) ?? suffix ?? "CORE";
  const version = val(ontologyIri, `${OWL}versionInfo`) ?? "no version";
  if (!suffix) {
    coreVersion = version;
    coreIssued = val(ontologyIri, `${DCT}issued`) ?? "";
  }
  for (const q of quads) store.addQuad(q);
  moduleLog.push(`${label} (${version})`);
  console.log(`  fetched ${label} (${version}) — ${quads.length} quads`);
}

const writer = new Writer({
  prefixes: {
    eudpp: "https://w3id.org/eudpp#",
    owl: "http://www.w3.org/2002/07/owl#",
    rdf: RDF,
    rdfs: RDFS,
    xsd: "http://www.w3.org/2001/XMLSchema#",
    dcterms: DCT,
    skos: "http://www.w3.org/2004/02/skos/core#",
    schema: "https://schema.org/",
    vann: "http://purl.org/vocab/vann#",
  },
});
writer.addQuads(store.getQuads(null, null, null, null));

const body = await new Promise<string>((resolve, reject) =>
  writer.end((err, result) => (err ? reject(err) : resolve(result))),
);

const header = [
  `# CIRPASS-2 EUDPP Core Ontology — upstream mirror (v${coreVersion}${coreIssued ? `, issued ${coreIssued}` : ""}).`,
  "# Verbatim merge of the published module exports (Semantic Treehouse,",
  "# dpp.vocabulary-hub.eu, via the w3id.org/eudpp redirects); upstream IRIs preserved,",
  "# nothing rebranded. Generated by scripts/sync-eudpp.ts (pnpm run sync:eudpp).",
  `# Modules: ${moduleLog.join("; ")}.`,
  "#",
  "# Upstream license: Apache License 2.0 (CC BY 4.0 fallback as a document),",
  "# (c) CIRPASS-2 project / TalTech.",
  "",
].join("\n");

writeFileSync(OUT, header + body);
console.log(`\nWrote ${OUT}`);
console.log(`  ${store.size} quads across ${MODULES.length} modules`);
