/**
 * Mirror the upstream GS1 Rail Vocabulary (published by GS1 AISBL with
 * GS1 Switzerland at https://gs1-epcis-reg.org/rail/) into this repo so
 * our build pipeline can index it on ref.openepcis.io.
 *
 * Run on demand whenever upstream publishes a new version:
 *
 *   pnpm sync:rail
 *
 * The upstream vocabulary is only published as JSON-LD (the .ttl link in
 * the upstream HTML index 404s as of 2026-05). This script converts the
 * JSON-LD to Turtle preserving the upstream namespace, copies the
 * JSON-LD context, the two SHACL files, and the three example documents
 * verbatim into extensions/upstream/gs1-rail/.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Parser as N3Parser, Store, Writer as N3Writer, DataFactory } from "n3";
import jsonld from "jsonld";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const MODULE_DIR = path.join(ROOT, "extensions/upstream/gs1-rail");

const RAIL_NS = "https://gs1-epcis-reg.org/rail/voc/data#";
const UPSTREAM_BASE = "https://gs1-epcis-reg.org/rail";

interface MirrorTarget {
  url: string;
  outFile: string;
}

const VERBATIM: MirrorTarget[] = [
  { url: `${UPSTREAM_BASE}/rail-context.jsonld`, outFile: "context/rail-context.jsonld" },
  { url: `${UPSTREAM_BASE}/voc/data/Rail-SHACL.json`, outFile: "validation/Rail-SHACL.json" },
  { url: `${UPSTREAM_BASE}/voc/data/Rail-EPCIS-SHACL-Generic.json`, outFile: "validation/Rail-EPCIS-SHACL-Generic.json" },
  { url: `${UPSTREAM_BASE}/examples/Example1.jsonld`, outFile: "examples/Example1.jsonld" },
  { url: `${UPSTREAM_BASE}/examples/Example2.jsonld`, outFile: "examples/Example2.jsonld" },
  { url: `${UPSTREAM_BASE}/examples/Example3.jsonld`, outFile: "examples/Example3.jsonld" },
];

const VOCAB_URL = `${UPSTREAM_BASE}/voc/data/gs1RailVoc.jsonld`;
const VOCAB_TTL_OUT = "ontology/gs1RailVoc.ttl";

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { headers: { Accept: "application/ld+json, application/json" } });
  if (!res.ok) throw new Error(`fetch ${url}: ${res.status}`);
  return await res.text();
}

async function writeFile(rel: string, text: string): Promise<void> {
  const full = path.join(MODULE_DIR, rel);
  await fs.mkdir(path.dirname(full), { recursive: true });
  await fs.writeFile(full, text, "utf8");
  console.log(`  wrote ${path.relative(ROOT, full)} (${text.length} bytes)`);
}

/**
 * Convert the upstream JSON-LD vocabulary to Turtle, preserving the
 * upstream namespace https://gs1-epcis-reg.org/rail/voc/data# verbatim.
 *
 * jsonld.toRDF produces N-Quads; we re-parse with N3 and re-emit as
 * Turtle so the output uses prefix declarations our build pipeline
 * already recognises.
 */
async function convertVocabToTurtle(jsonldText: string): Promise<string> {
  const doc = JSON.parse(jsonldText);
  const nquads = (await jsonld.toRDF(doc, { format: "application/n-quads" })) as unknown as string;

  const store = new Store();
  await new Promise<void>((resolve, reject) => {
    const parser = new N3Parser({ format: "application/n-quads" });
    parser.parse(nquads, (err, quad) => {
      if (err) return reject(err);
      if (quad) store.addQuad(quad);
      else resolve();
    });
  });

  const writer = new N3Writer({
    prefixes: {
      rail: RAIL_NS,
      gs1: "https://ref.gs1.org/voc/",
      schema: "https://schema.org/",
      epcis: "https://ref.gs1.org/epcis/",
      cbv: "https://ref.gs1.org/cbv/",
      rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
      rdfs: "http://www.w3.org/2000/01/rdf-schema#",
      owl: "http://www.w3.org/2002/07/owl#",
      xsd: "http://www.w3.org/2001/XMLSchema#",
      dc: "http://purl.org/dc/terms/",
      dc11: "http://purl.org/dc/elements/1.1/",
      voaf: "http://www.w3.org/ns/voaf#",
      vann: "https://vocab.org/vann/#",
      sw: "http://www.w3.org/2003/06/sw-vocab-status/ns#",
      skos: "http://www.w3.org/2004/02/skos/core#",
    },
  });

  return await new Promise<string>((resolve, reject) => {
    writer.addQuads(store.getQuads(null, null, null, null));
    writer.end((err, result) => {
      if (err) reject(err);
      else
        resolve(
          [
            "# GS1 Rail Vocabulary — Turtle serialisation",
            `# Source: ${VOCAB_URL}`,
            "# Generated by scripts/sync-rail.ts; do not edit by hand.",
            `# Synced: ${new Date().toISOString()}`,
            "",
            result,
          ].join("\n")
        );
    });
  });
}

async function main(): Promise<void> {
  console.log(`Mirroring GS1 Rail vocabulary from ${UPSTREAM_BASE}/ ...`);

  console.log(`Fetching ${VOCAB_URL}`);
  const vocabJsonld = await fetchText(VOCAB_URL);
  const vocabTtl = await convertVocabToTurtle(vocabJsonld);
  await writeFile(VOCAB_TTL_OUT, vocabTtl);

  for (const t of VERBATIM) {
    console.log(`Fetching ${t.url}`);
    const text = await fetchText(t.url);
    if (text.length === 0) {
      console.log(`  skipped ${t.outFile} — upstream returned 0 bytes`);
      continue;
    }
    await writeFile(t.outFile, text);
  }

  const overridesPath = path.join(MODULE_DIR, "context/.context-overrides.json");
  try {
    await fs.access(overridesPath);
  } catch {
    await writeFile("context/.context-overrides.json", "{}\n");
  }

  console.log(`\nDone. Review changes with:  git diff -- ${path.relative(ROOT, MODULE_DIR)}`);
  console.log(`Then run:  pnpm build:json && pnpm build:context && pnpm validate:examples`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
