/**
 * GEFEG BatteryPass-Ready conformance harness (offline).
 *
 * The GEFEG test environment (https://batterypass-ready.gefeg.com/) is live. Its
 * server enforces a stricter schema than the downloadable static files (no
 * `required`, wrong Stationary root key, different key names). We mirror the LIVE
 * contract in extensions/eu/battery/validation/gefeg-live/<RootKey>.schema.json
 * (generated by scripts/build-gefeg-live-schema.ts from the live required-sets +
 * verified-valid fixtures) and validate against those here.
 *
 * For each of the four battery categories:
 *   1. SCHEMA       export the flat OpenEPCIS passport to the GEFEG upload shape
 *                   (scripts/export-batterypass-gefeg.ts) and ajv-validate it
 *                   against the live-derived schema. Negative: dropping a
 *                   required group field is rejected.
 *   2. PLAUSIBILITY cross-field sanity the live tool defers to a future release
 *                   (it checks structure only): voltage ordering, percent ranges,
 *                   positivity, UTC timestamps.
 *
 * The authoritative check remains the live API (scripts/validate-batterypass-live.ts);
 * all four fixtures here are verified VALID against it (2026-06-17).
 *
 * Run: pnpm test
 */

import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { exportGefeg, lastPopulatedCount } from "./export-batterypass-gefeg.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SCHEMA_DIR = join(ROOT, "extensions/eu/battery/validation/gefeg-live");
const SOURCE = join(ROOT, "extensions/eu/battery/examples/batterypass-ready/other-industrial.source.json");

const CATEGORIES = [
  { param: "ev", rootKey: "EV" },
  { param: "lmt", rootKey: "LMT" },
  { param: "other-industrial", rootKey: "OtherIndustrial2kWh" },
  { param: "stationary", rootKey: "StationaryIndustrial2kWh" },
];
const PRIMARY = "other-industrial";

interface TestResult { name: string; passed: boolean; detail?: string; }
const results: TestResult[] = [];
const record = (name: string, passed: boolean, detail?: string) => results.push({ name, passed, detail });
const loadJson = <T = any>(p: string): T => JSON.parse(readFileSync(p, "utf-8")) as T;

const ajv = new (Ajv2020 as unknown as { new (o: object): any })({ strict: false, allErrors: true });
(addFormats as unknown as (a: unknown) => void)(ajv);

const describe = (errs: any) =>
  Array.isArray(errs) ? errs.slice(0, 5).map((e) => `${e.instancePath || "(root)"} ${e.message}`).join("; ") : "";

type Doc = Record<string, any>;

// =============================================================================
// 1. SCHEMA group — every category against its live-derived schema
// =============================================================================
function runSchemaTests(source: Doc): Doc {
  let primaryExport: Doc = {};
  for (const c of CATEGORIES) {
    const exported = exportGefeg(source, c.param) as Doc;
    const coverage = lastPopulatedCount();
    if (c.param === PRIMARY) primaryExport = exported;

    const schema = loadJson(join(SCHEMA_DIR, `${c.rootKey}.schema.json`));
    const validate = ajv.compile(schema);
    const ok = validate(exported);
    record(
      `SCHEMA: ${c.param} export validates against live-derived ${c.rootKey}.schema.json`,
      !!ok,
      ok ? `${coverage} attributes populated` : describe(validate.errors)
    );

    // Negative: drop a required identifier field → must be rejected.
    const broken: Doc = JSON.parse(JSON.stringify(exported));
    delete broken[c.rootKey].IdentifiersAndProductData.BatteryModelIdentifier;
    record(
      `SCHEMA neg: ${c.param} missing BatteryModelIdentifier is rejected`,
      !validate(broken),
      ""
    );
  }
  return primaryExport;
}

// =============================================================================
// 2. PLAUSIBILITY group (exceeds the live tool's current structure-only scope)
// =============================================================================
const num = (v: any): number | undefined => (typeof v === "number" ? v : undefined);
const isUtc = (s: unknown) => typeof s === "string" && /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?(\.\d+)?Z$/.test(s);

function runPlausibilityTests(exported: Doc): void {
  const m = exported.OtherIndustrial2kWh as Doc;
  const perf = m.PerformanceAndDurability as Doc;
  const ident = m.IdentifiersAndProductData as Doc;
  const circ = m.CircularityAndResourceEfficiency as Doc;
  const carbon = m.BatteryCarbonFootprint as Doc;

  const min = num(perf.MinimumVoltage?.voltValue);
  const nom = num(perf.NominalVoltage?.voltValue);
  const max = num(perf.MaximumVoltage?.voltValue);
  record(
    "PLAUSIBILITY: minimumVoltage ≤ nominalVoltage ≤ maximumVoltage",
    [min, nom, max].some((x) => x === undefined) || ((min as number) <= (nom as number) && (nom as number) <= (max as number)),
    `min=${min} nom=${nom} max=${max}`
  );

  const pcts = [...Object.values(circ), perf.CapacityThresholdForExhaustion, perf.InitialRoundTripEnergyEfficiency]
    .map((o) => num((o as Doc)?.percentageValue))
    .filter((v): v is number => v !== undefined);
  record("PLAUSIBILITY: percent values ∈ [0, 100]", pcts.every((v) => v >= 0 && v <= 100), `${pcts.length} checked`);

  record("PLAUSIBILITY: expected lifetime years > 0", (num(perf.ExpectedLifetimeInCalendarYears) ?? 1) > 0);
  record("PLAUSIBILITY: Date-timeOfLatestUpdateOfDPP is UTC", isUtc(ident["Date-timeOfLatestUpdateOfDPP"]));
  record(
    "PLAUSIBILITY: carbon footprint per functional unit > 0",
    (num(carbon?.BatteryCarbonFootprintPerFunctionalUnit?.["kgCO2-equivalentPerKilowattHourValue"]) ?? 1) > 0
  );

  // Negative: out-of-range percent must trip the rule.
  const v = 140;
  record("PLAUSIBILITY neg: percent 140 is out of range", !(v >= 0 && v <= 100));
}

// =============================================================================
const source = loadJson<Doc>(SOURCE);
const primary = runSchemaTests(source);
runPlausibilityTests(primary);

const passed = results.filter((r) => r.passed).length;
const failed = results.length - passed;
console.log("\nGEFEG BatteryPass-Ready conformance run (offline, live-derived schemas)\n" + "=".repeat(60));
for (const r of results) console.log(`  ${r.passed ? "PASS" : "FAIL"}  ${r.name}${r.detail ? `  — ${r.detail}` : ""}`);
console.log("=".repeat(60));
console.log(`${passed} passed, ${failed} failed, ${results.length} total`);
if (failed > 0) process.exit(1);
